"""
Django settings for Justice_For_All project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from .info import *
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i!s$gvw)1i33hp+uxq5-=+)rw8!1-h+ye@93igiek)97i(x1t9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'advocate_authentication',
    'signup',
    'login',
    'logout',
    'home_page',
    'contact',
    'gallery',
    'about_us',
    'advocate',
    'AFAP',
    'AFAPP',
    'AFBC',
    'AR',
    'BFL',
    'BOCC',
    'CA',
    'CBN',
    'CIGST',
    'CIIEC',
    'CITA',
    'CM',
    'COGST',
    'CRLA',
    'CRR',
    'DACC',
    'DC',
    'DIPPC',
    'Dis',
    'Disco',
    'DOPF',
    'DSC',
    'EC',
    'ESIF',
    'ESIR',
    'F',
    'FA',
    'FARFYPLC',
    'FATO',
    'FCA',
    'FLA',
    'FraA',
    'GAFAL',
    'GBLA',
    'GBLO',
    'GC',
    'GD',
    'GSTR',
    'Hearing',
    'IECR',
    'IP',
    'ISOR',
    'ITA',
    'JVA',
    'LA',
    'LALA',
    'LLPR',
    'LN',
    'LoanAgre',
    'LTI',
    'LUTA',
    'LWFR',
    'MA',
    'MD',
    'MOS',
    'MOT',
    'MOU',
    'MSA',
    'NDA',
    'NIDGICR',
    'OPCR',
    'PAPOA',
    'PFAESIF',
    'PFAESIR',
    'PFF',
    'PFreg',
    'PLCR',
    'PLCWIAFS',
    'PostDisc',
    'POW',
    'PP',
    'PreFili',
    'PRS',
    'PS',
    'PSA',
    'PTF',
    'PTFD',
    'PTFE',
    'PTR',
    'RANBFCCII',
    'RATSGBAI',
    'RC',
    'RelChan',
    'RTATO',
    'SAEAR',
    'SCR',
    'SD',
    'SHA',
    'SOAICII',
    'SPA',
    'SR',
    'SSIMSMER',
    'TAN',
    'TLR',
    'TMW',
    'TOS',
    'TOSAPP',
    'TOT',
    'TR',
    'TRADErenew',
    'Trial',
    'TS',
    'TW',
    'USACC',
    'USACI',
    'VA',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Justice_For_All.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Justice_For_All.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
            }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
